# Generated by Django 3.1.5 on 2025-02-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0007_auto_20250217_1140'),
    ]

    operations = [
    ]
